### PR TITLE
#1: Initial implementation

### PR DESCRIPTION
**Pull request by mdrlzy**
#1

### CODE REVIEW

**Comment by mdrlzy** [comment]
- [x] Handle edit intent
- [x] Fix write permissions request (ask not only at start)

@kirillt What else?

**Comment by kirillt** [comment]
@mdrlzy this app already feels much better than our legacy version :)

Minor issues:
- [x] ~~Probably we should decrease drawing threshold — when I just tap, nothing happens, so it's difficult to draw dots in "!" or "?"~~ #4
- [x] Default black/white balance is — user could be confused while changing color (e.g. from red to green), because they would still draw black
- [x] KtLint would be nice

I'll compose list of desired features soon.

**Comment by kirillt** [comment]
@mdrlzy
Features to be implemented: https://github.com/ARK-Builders/ARK-Retouch/issues/1#issuecomment-1311372123
We can split them into separate PR, of course.

Couple of other minor issues:
- [x] The app must be treated as "editor". E.g. when you see a picture in stock Gallery app, usually there is "more" button and an action like "open in other editors" which lists registered editors. Our legacy ARK Retouch is visible there, on my phone.
- [x] Default size for drawing area must be the whole screen, control elements should be floating on top of it.

**Comment by mdrlzy** [comment]
> Probably we should decrease drawing threshold — when I just tap, nothing happens, so it's difficult to draw dots in "!" or "?"

> Default black/white balance is — user could be confused while changing color (e.g. from red to green), because they would still draw black

Both points require library changes, which is not possible at the moment.

**Comment by kirillt** [comment]
Minor issues:
- [x] In color picker, there is a bar. Leftmost position gives us black color.
      But rightmost position doesn't give us white, it's just very bright color.
- [x] `Back` event should cancel last action.
- [x] Before leaving the app, if there were any actions, user should be asked for confirmation.
      Exception is when user just saved the picture.
- [x] ~~In this version we have `undo` operation, so~~ maybe we need explicit `quit` button.
- [x] Legacy version quits immediately after saving, **if it was started with edit intent**.
      This is convenient for multiple editions in a row. We could add preference for this.

Bug:
- [x] If you start the app with edit intent, it opens picture by path in the arguments to edit it.
      If this coincides with first run on the system, the app will ask for storage permissions.
      After granting them, the app starts with blank page instead of the picture.

Performance:
- [x] ~~Drawing on huge pictures is slow (try full-screen screenshot from laptop).~~
      ~~I can provide video record and test data later.~~ Doesn't reproduce.

**Comment by kirillt** [comment]
- [x] ~~We should decrease drawing threshold — when I just tap, nothing happens, so it's difficult to draw dots in "!" or "?" These invisible dots still take a "turn" to cancel them.~~ #4 
- [x] ~~Semi-transparent colors make the line to be "made of circles", these circles overlap resulting in wrong color. But if you draw several lines and undo the last one, the first one becomes of correct color. If you save the image, incorrect version is saved (visible without undoing).~~ #3 
- [x] ~~Thickness selector sometimes closes unpredictably — on Android 11 with pen, only in landscape layout. It closes when the pen points at the selector, but not touches the screen (bluetooth-enabled pen allows to point like mouse). In portrait layout the bug doesn't reproduce.~~ #5 
- [x] Should be possible to draw really thin lines, ideally just 1 pixel thick.

**Review by kirillt — APPROVED** [review]
Awesome

**Pull request merged**
