### PR TITLE
#8: Eyedropper

### PR DESCRIPTION
**Pull request by shubertm**
#8

### CODE REVIEW

**Comment by kirillt** [comment]
@ShubertMunthali good start, I see color changing when I tap with finger or point with pen. But current color isn't remembered, I can't draw with the picked color.

**Comment by shubertm** [comment]
> @ShubertMunthali good start, I see color changing when I tap with finger or point with pen. But current color isn't remembered, I can't draw with the picked color.

Will fix it later

**Comment by kirillt** [comment]
- [x] Let's forbid picking transparent color (from uncolored pixels in drawing mode).
       This is confusing and also when user wants to change color after, even on selecting e.g. blue, it will be transparent because user needs also adjust transparency level.
- [x] With finger it works awesome, but with pen now it doesn't work.
       Hover event immediately confirms the color. Ideally, hover event should change color temporarily like it was before.
       And tap event must confirm the color selection.

**Comment by shubertm** [comment]
Alright

**Review by kirillt — APPROVED** [review]
Awesome feature!

**Pull request merged**
