### PR TITLE
#30: Rotation behaves differently in drawing mode

### PR DESCRIPTION
**Pull request by pgpathan22**
#30

### CODE REVIEW

**Comment by pgpathan22** [comment]
#27 is also resolved in this.

**Comment by kirillt** [comment]
Also fixes #27, right?

**Comment by pgpathan22** [comment]
> @pgpathan22 on my device #27 isn't solved by this PR:
> 
>     1. Open Retouch.
> 
>     2. Switch to drawing mode, draw a line.
> 
>     3. Turn the device.
> 
>     4. `[undo]` button disappears.

did you test on this build?
https://github.com/ARK-Builders/ARK-Retouch/actions/runs/2954585228

**Comment by kirillt** [comment]
@pgpathan22 it is fixed indeed, sorry.

**Review by kirillt — APPROVED** [review]

**Pull request merged**
