### PR TITLE
Extract image loader code & encapsulate logic

### PR DESCRIPTION
**Pull request by hieuwu**
- Move functions that handle image into editManager
- Extract logic of loading image & to be out of ViewModel. The `BitmapLoader` contains logic of loading image from path, uri into `EditManager` & hides the logic of glide for bitmap loading

### CODE REVIEW

**Comment by kirillt** [comment]
@shubertm could you check how difficult are the conflicts?

@hieuwu we have big stale PR from `develop` to `main`, I guess if we merge yours into `develop` it should be safer. But if you prefer, feel free changing base back to `main`. We want to get rid of `develop` for now.

**Comment by hieuwu** [comment]
> @shubertm could you check how difficult are the conflicts?
> 
> @hieuwu we have big stale PR from `develop` to `main`, I guess if we merge yours into `develop` it should be safer. But if you prefer, feel free changing base back to `main`. We want to get rid of `develop` for now.

Let's merge into develop then. We could prefer merging that big PR first. I can handle this later

**Comment by shubertm** [comment]
> > @shubertm could you check how difficult are the conflicts?
> > @hieuwu we have big stale PR from `develop` to `main`, I guess if we merge yours into `develop` it should be safer. But if you prefer, feel free changing base back to `main`. We want to get rid of `develop` for now.
> 
> Let's merge into develop then. We could prefer merging that big PR first. I can handle this later

Yes, we should merge the PR #126 first, changes here are small. Could be resolved with main later. And because the file structure was also refactored.

**Comment by shubertm** [comment]
Good work @hieuwu :rocket: I have looked at the code, looks good. Let's minimize `EditViewModel` and `EditManager` more. I will approve once all conflicts are resolved

**Review by shubertm — COMMENTED** [review]
Let's merge #126 and resolve conflicts first

**Pull request closed without merging**
